baseURL: https://lukasz.laniewski.wollk.pl/
languageCode: en-us
title: "Łukasz Łaniewski-Wołłk"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: UA-XXXXXXXXX-X

# Enable Disqus forum
disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Copyright Notice
  copyright: © 2020 Copyright.

  # Meta description for your site.  This will help the search engines to find your site.
  description: Portfolio and personal blog of Łukasz Łaniewski-Wołłk

  # background image of the landing page
#  background: images/20130706_165855.jpg
  background: images/20151209_170008.jpg # fajne
#  background: images/20170710_173602_.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /assets/images/main-logo.png
    inverted: /assets/images/inverted-logo.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/llaniewski/llaniewski

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  customMenus:
  - name: TCLB
    url: https://tclb.io/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: true

  # some information about you
  author:
    name: "Łukasz Łaniewski-Wołłk"
    nickname: "Łukasz"
    image: "images/avatar.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: ""
      phone: ""
    # a summary of what you do
    summary:
    - Developer
    - Researcher

